/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Security.view.NavPanel'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'navpanel',
                    margins: '0 0 0 3',
                    region: 'west',
                    split: true
                },
                me.processTabs({
                    xtype: 'tabpanel',
                    region: 'center'
                }),
                {
                    xtype: 'toolbar',
                    margins: '0 0 3 0',
                    region: 'north',
                    items: [
                        {
                            xtype: 'button',
                            text: '系统注消'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    margins: '3 0 0 0',
                    region: 'south',
                    items: [
                        {
                            xtype: 'tbtext',
                            text: '万达信息股份有限公司版权所有V1.0'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processTabs: function(config) {
        config.plugins = [{
            ptype: 'tabclosemenu',
            closeTabText: '关闭标签',
            closeOthersTabsText: '关闭其它标签',
            closeAllTabsText: '关闭所有标签'
        }];
        return config;
    }

});