/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Security.view.UserGridPanel',
        'Security.view.RoleGridPanel',
        'Security.view.UserRolePanel',
        'Security.view.OrgaTree',
        'Security.view.RescTree'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    margins: '0 0 0 3',
                    region: 'west',
                    split: true,
                    width: 200,
                    layout: {
                        align: 'center',
                        defaultMargins: {
                            top: 20,
                            right: 20,
                            bottom: 20,
                            left: 20
                        },
                        type: 'vbox'
                    },
                    collapsible: true,
                    title: '系统功能导航栏',
                    items: [
                        {
                            xtype: 'image',
                            listeners: {
                                el: {
                                    click: function() {
                                            Ext.example.msg('提示', '你好，世界！');
                                        }
                                }
                            },
                            height: 64,
                            style: 'cursor: pointer',
                            width: 64,
                            alt: '用户管理',
                            src: 'images/user.png',
                            title: '用户管理'
                        },
                        {
                            xtype: 'image',
                            height: 64,
                            style: 'cursor: pointer',
                            width: 64,
                            src: 'images/role.png',
                            title: '角色管理'
                        },
                        {
                            xtype: 'image',
                            height: 64,
                            style: 'cursor: pointer',
                            width: 64,
                            src: 'images/orga.png',
                            title: '组织机构管理'
                        },
                        {
                            xtype: 'image',
                            height: 64,
                            style: 'cursor: pointer',
                            width: 64,
                            src: 'images/res.png',
                            title: '系统资源管理'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    plain: true,
                    items: [
                        {
                            xtype: 'usergrid'
                        },
                        {
                            xtype: 'rolegrid'
                        },
                        {
                            xtype: 'userrolepanel'
                        },
                        {
                            xtype: 'orgatree'
                        },
                        {
                            xtype: 'resctree'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    margins: '0 0 3 0',
                    region: 'north',
                    items: [
                        {
                            xtype: 'button',
                            text: '系统退出'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    margins: '3 0 0 0',
                    region: 'south',
                    items: [
                        {
                            xtype: 'tbtext',
                            text: '万达信息股份有限公司版权所有V1.0'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});