/*
 * File: app/view/NavPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.NavPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navpanel',

    width: 200,
    layout: {
        align: 'center',
        defaultMargins: {
            top: 20,
            right: 20,
            bottom: 20,
            left: 20
        },
        type: 'vbox'
    },
    collapsible: true,
    title: '系统功能导航栏',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    listeners: {
                        el: {
                            click: function() {
                                    addTab({controller: 'UserController', view: 'usergrid'});
                                }
                        }
                    },
                    height: 64,
                    style: 'cursor: pointer',
                    width: 64,
                    alt: '用户管理',
                    src: 'images/user.png',
                    title: '用户管理'
                },
                {
                    xtype: 'image',
                    listeners: {
                        el: {
                            click: function() {
                                	addTab({controller: 'RoleController', view: 'rolegrid'});
                                }
                        }
                    },
                    height: 64,
                    style: 'cursor: pointer',
                    width: 64,
                    src: 'images/role.png',
                    title: '角色管理'
                },
                {
                    xtype: 'image',
                    listeners: {
                        el: {
                            click: function() {
                                    addTab({controller: 'OrgaController', view: 'orgatree'});
                                }
                        }
                    },
                    height: 64,
                    style: 'cursor: pointer',
                    width: 64,
                    src: 'images/orga.png',
                    title: '组织机构管理'
                },
                {
                    xtype: 'image',
                    listeners: {
                        el: {
                            click: function() {
                                    addTab({controller: 'RescController', view: 'resctree'});
                                }
                        }
                    },
                    height: 64,
                    style: 'cursor: pointer',
                    width: 64,
                    src: 'images/res.png',
                    title: '系统资源管理'
                }
            ]
        });

        me.callParent(arguments);
    }

});