/*
 * File: app/view/RoleRescPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.RoleRescPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.rolerescpanel',

    requires: [
        'Security.view.RoleGrid',
        'Security.view.RescTree'
    ],

    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    bodyPadding: 1,
    title: '角色管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'rolegrid',
                    flex: 1
                },
                {
                    xtype: 'splitter',
                    size: 4
                },
                {
                    xtype: 'resctree',
                    listeners: {
                        afterrender: function(tree) {
                            tree.getRootNode().set('checked', false);
                         	tree.expandAll();
                        }
                    },
                    checkedTree: true,
                    title: '系统资源',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});