/*
 * File: app/view/RoleListWin.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.RoleListWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.rolelistwin',

    height: 335,
    width: 555,
    layout: {
        type: 'fit'
    },
    closeAction: 'hide',
    constrainHeader: true,
    title: '角色列表',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                me.processMyGridPanel1({
                    xtype: 'gridpanel',
                    columnLines: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: '名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'code',
                            text: '代码'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'description',
                            text: '描述',
                            flex: 1
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            displayInfo: true
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'triggerfield',
                                    width: 254,
                                    fieldLabel: '名称',
                                    labelWidth: 55,
                                    emptyText: '请输入一个角色名称！'
                                }
                            ]
                        }
                    ]
                })
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: '确定'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                button.up('window').hide();
                            },
                            text: '关闭'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processMyGridPanel1: function(config) {
        config.store = Ext.create('Security.store.Role');
        config.dockedItems[0].store = config.store;

        var searchfield = config.dockedItems[1].items[0];

        searchfield.xtype = 'searchfield';
        searchfield.paramName = 'search_name_like';
        searchfield.store = config.store;

        return config;
    }

});