/*
 * File: app/view/RoleListWin.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.RoleListWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.rolelistwin',

    height: 335,
    width: 593,
    layout: {
        type: 'fit'
    },
    constrainHeader: true,
    title: '角色列表',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: '确定'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                button.up('window').close();
                            },
                            text: '关闭'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    columnLines: true,
                    store: 'Role',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: '名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'code',
                            text: '代码'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'description',
                            text: '描述',
                            flex: 1
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'Role'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});