/*
 * File: app/view/UserRoleRescPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.UserRoleRescPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.userrolerescpanel',

    requires: [
        'Security.view.UserGrid',
        'Security.view.RoleGrid',
        'Security.view.RescTree'
    ],

    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: '用户授权',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1.8,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'usergrid',
                            removeDockedItems: true,
                            title: '用户列表',
                            flex: 1
                        },
                        {
                            xtype: 'splitter',
                            size: 4
                        },
                        {
                            xtype: 'rolegrid',
                            removeDockedItems: true,
                            newStore: true,
                            title: '角色列表',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'splitter',
                    size: 4
                },
                {
                    xtype: 'resctree',
                    checkedTree: true,
                    title: '系统资源',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});