/*
 * File: app/view/UserGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UserGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.usergrid',

    title: '用户列表',
    columnLines: true,
    store: 'UserStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'username',
                    text: 'Username'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'loginName',
                    text: 'LoginName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'password',
                    text: 'Password'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sex',
                    text: 'Sex'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userCard',
                    text: 'UserCard'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'phone',
                    text: 'Phone'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'fax',
                    text: 'Fax'
                }
            ]
        });

        me.callParent(arguments);
    }

});