/*
 * File: app/view/UserWin.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.view.UserWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.userwin',

    width: 331,
    constrain: true,
    layout: {
        type: 'fit'
    },
    constrainHeader: true,
    title: '用户信息',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    fieldDefaults: {
                        labelWidth: 70
                    },
                    items: [
                        {
                            xtype: 'hiddenfield',
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '用户名',
                            name: 'username',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '登录名',
                            name: 'loginName',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '密码',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '性别',
                            name: 'sex',
                            value: '男',
                            allowBlank: false,
                            editable: false,
                            queryMode: 'local',
                            store: [
                                '男',
                                '女'
                            ]
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '用户证号',
                            name: 'userCard'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '电话',
                            name: 'phone'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '传真',
                            name: 'fax'
                        },
                        me.processOrgaid({
                            xtype: 'triggerfield',
                            anchor: '100%',
                            fieldLabel: '组织机构',
                            name: 'orga.id',
                            allowBlank: false
                        })
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        this.up('window').close();
                                    },
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processOrgaid: function(config) {
        config.xtype = 'treepicker';
        config.displayField = 'text';
        config.forceSelection = true;
        config.autoScroll = true

        config.store = Ext.create('Security.store.Orga', {
            autoLoad: true
        });
        return config;
    }

});