/*
 * File: app/controller/OrgaController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.controller.OrgaController', {
    extend: 'Ext.app.Controller',

    onTreepanelItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        e.stopEvent();
        var treeMenu = Ext.create('Ext.menu.Menu',{
            items: [{
                text: '添加',
                handler: function(button) {
                    var orgaWin = Ext.create('Security.view.OrgaWin');
                    orgaWin.show(button);
                }
            }, {
                xtype: 'menuseparator'
            }, {
                text: '编辑',
                handler: function(button) {
                    var orgaWin = Ext.create('Security.view.OrgaWin'),
                        form = orgaWin.child('form');

                    form.loadRecord(record);
                    orgaWin.show(button);
                }
            }, {
                text: '删除',
                handler: function(button) {
                    if (record.isLeaf()) {
                        Ext.create('Security.model.Orga', {
                            id: record.get('id')
                        }).destroy({
                            success: function() {
                                record.destroy();
                            }
                        });
                    }
                } 
            }]
        });
        treeMenu.showAt(e.xy);
    },

    init: function(application) {
        this.control({
            "treepanel": {
                itemcontextmenu: this.onTreepanelItemContextMenu
            }
        });
    }

});
