/*
 * File: app/controller/RescController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.controller.RescController', {
    extend: 'Ext.app.Controller',

    models: [
        'Resc'
    ],
    stores: [
        'Resc'
    ],
    views: [
        'RescTree',
        'RescWin'
    ],

    refs: [
        {
            ref: 'rescWin',
            selector: 'rescwin'
        }
    ],

    onTreepanelItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        e.stopEvent();
        var treeMenu = Ext.create('Ext.menu.Menu',{
            items: [{
                text: '添加',
                handler: function(button) {
                    var rescWin = Ext.create('Security.view.RescWin'),
                        form = rescWin.child('form');

                    form.loadRecord(Ext.create('Security.model.Resc'));
                    rescWin.show(button);
                }
            }, {
                xtype: 'menuseparator'
            }, {
                text: '编辑',
                handler: function(button) {
                    var rescWin = Ext.create('Security.view.RescWin'),
                        form = rescWin.child('form');

                    form.loadRecord(record);
                    rescWin.show(button);
                }
            }, {
                text: '删除',
                handler: function(button) {
                    if (record.isLeaf()) {
                        Ext.create('Security.model.Resc', {
                            id: record.get('id')
                        }).destroy({
                            success: function() {
                                record.remove();
                            }
                        });
                    }
                } 
            }]
        });
        treeMenu.showAt(e.xy);
    },

    saveResc: function(button, e, eOpts) {
        var win = this.getRescWin(),
            form = win.child('form'),
            rescStore = this.getRescStore(),
            parentId = form.getRecord().get('parentId');

        if (!parentId) parentId = 0;

        var resc = Ext.create('Security.model.Resc', form.getValues());

        resc.set('parent', {'id': parentId});

        resc.save({
            success: function() {
                rescStore.reload();
                win.close();
            }
        });
    },

    init: function(application) {
        this.control({
            "resctree": {
                itemcontextmenu: this.onTreepanelItemContextMenu
            },
            "rescwin button[text='保存']": {
                click: this.saveResc
            }
        });
    }

});
