/*
 * File: app/controller/UserRoleController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Security.controller.UserRoleController', {
    extend: 'Ext.app.Controller',

    stores: [
        'User',
        'Role'
    ],
    views: [
        'UserRolePanel'
    ],

    userGridItemClick: function(dataview, record, item, index, e, eOpts) {
        var userId = record.get('id'),
            roleGrid = Ext.ComponentQuery.query('userrolepanel').pop().child('rolegrid'),
            roleStore = roleGrid.getStore();

        roleStore.getProxy().url = 'roles/findByUserId';
        roleStore.getProxy().setExtraParam('userId', userId);

        roleStore.load();
    },

    init: function(application) {
        this.control({
            "userrolepanel > usergrid": {
                itemclick: this.userGridItemClick
            }
        });
    }

});
